require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  EnabledByDefault: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/MissingElse:
  Enabled: false
