require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  EnabledByDefault: true

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/MissingElse:
  Enabled: false
